sudo: required
services:
  - docker
env:
  matrix:
    - DOCKER_COMPOSE_VERSION=1.22.0
  global:
    secure: eo3VvGLZIPuvP5IN8wNPj9KGM88VJ1Wu6R/1qtYvuDEbIWxs2Lf1ZXiXHjCBMo3xUIvFZ/4JWwGaak37pTv1TGvDnO0TcaeGFEjpmOY0umjOuG7vRqGtaX+eX4UfYoSNSJCAUFUqppu/rW/qqKGyqaR25RQnR5wcBpvcoymiROq3krnkCs8FB2iLOgA8ITFMqWNxmcuH+QP76AAtGl95KE97b78EVBv1FKQ24GyUbW+JpWuGSxKJSUsWaq+AZ4mLETexS1SBLETlvDA2SJjWgXgP2IWtwFSIip4Jvy98nLYe7iC2yd4xWvLFFLk+3KmBqD6TvUlRGc618cEWwXtfGw/s/Q2M1yTw3mzYganfgnbb7VOe99BD7tHTLwmj/7NRjfRSed+W72epRC5ke7d9DQie2rsuCSp/owO667+kMBP59ulAgOivHKF5f32JGso/niDQVTouwrzvzjzwg2NIfL+zEzq/0qWX/4pFzbYNg5ooTwXcmWOfwMsxIa4IWcaTQPPu7mpt8xq5cWsNmVG2zcj6jLO2VEVQhV1JA1qYcmjjyUZYOCXXsRzWgw2y/AreOrY8mHcxsqKk/ApVrjxvLciC9KSJVZmoTHpwefd5vPBUehxin2ewBlEBTVpIg3JTK7Dkb1/pH/wPRzDSxw67PA3IzJz9fsuRRg/1KYMHqE4=
before_install:
  - openssl aes-256-cbc -k "$encrypted_key" -in ./travis_rsa.enc -out ~/.ssh/travis_rsa -d
  - sudo chmod 600 ~/.ssh/travis_rsa
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose -v
script:
  - cp .env.example .env
  - docker-compose run --rm backend npm install
  - docker-compose run --rm frontend npm install
  - docker-compose run --rm frontend npm run build
branches:
  only:
    - master
    - develop
deploy:
  - provider: script
    skip_cleanup: true
    script: ".travis/production.sh"
    on:
      branch: master
