version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
  backend:
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
    env_file:
      - .env
    ports:
      - 3001:3000
    volumes:
      - ./backend:/backend
      - /backend/node_modules