version: "3.5"
services:
  frontend:
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    env_file:
      - .env
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    networks:
      - frontend
  backend:
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    networks:
      - backend 
  web:
    build: .docker/web
    ports:
      - "8080:80"
      - "8443:443"
    env_file:
      - .env
    networks:
      - frontend
      - backend
networks:
  backend:
  frontend: