version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules