version: "3.5"
services:
  frontend:
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    env_file:
      - .env
    volumes:
      - ./frontend:/frontend
    networks:
      - frontend
  backend:
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/backend
    networks:
      - backend 
  web:
    build: .docker/web
    depends_on:
      - frontend
      - backend
    ports:
      - "${APP_HTTP_PORT}:80"
      - "${APP_HTTPS_PORT}:443"
    env_file:
      - .env
    networks:
      - frontend
      - backend
  mongodb:
    image: mongo:4.0
    volumes:
      - ./.mongodb:/data/db
    env_file:
      - .env
    networks:
      - backend
  elasticsearch:
    image: elasticsearch:6.4.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - .esdata:/usr/share/elasticsearch/data:rw
    ports:
      - 9200:9200
    networks:
      - backend
networks:
  backend:
  frontend:
volumes:
  .esdata:
    driver: local