export const TODO_SEND_ADD_ITEM_REQUEST = 'TODO_SEND_ADD_ITEM_REQUEST';
export const TODO_SEND_GET_ALL_ITEMS_REQUEST = 'TODO_SEND_GET_ALL_ITEMS_REQUEST';
export const TODO_SEND_DELETE_ITEM_REQUEST = 'TODO_SEND_DELETE_ITEM_REQUEST';
export const TODO_SEND_CHANGE_TEXT_REQUEST = 'TODO_SEND_CHANGE_TEXT_REQUEST';
export const TODO_SEND_COMPLETE_ITEM_REQUEST = 'TODO_SEND_COMPLETE_ITEM_REQUEST';

export const LOAD_TODO_ITEMS = 'LOAD_TODO_ITEMS';
export const TODO_ADD_ITEM = 'TODO_ADD_ITEM';
export const TODO_DELETE_ITEM = 'TODO_DELETE_ITEM';
export const TODO_COMPLETE_ITEM = 'TODO_COMPLETE_ITEM';
export const TODO_EDIT_ITEM = 'TODO_EDIT_ITEM';
export const TODO_UNDO_ITEM = 'TODO_UNDO_ITEM';
export const TODO_REDO_ITEM = 'TODO_REDO_ITEM';
export const TODO_TAKE_SNAPSHOT = 'TODO_TAKE_SNAPSHOT';
