export const TODO_ADD_ITEM = 'TODO_ADD_ITEM';
export const TODO_DELETE_ITEM = 'TODO_DELETE_ITEM';
export const TODO_COMPLETE_ITEM = 'TODO_COMPLETE_ITEM';
export const TODO_EDIT_ITEM = 'TODO_EDIT_ITEM';
export const TODO_UNDO_ITEM = 'TODO_UNDO_ITEM';
export const TODO_REDO_ITEM = 'TODO_REDO_ITEM';
